#!/usr/bin/env node
// Bumps the patch version, stamps it into web/version.js and web/sw.js's
// cache name (so installed PWAs actually pick up the new build instead of
// serving a stale cached one), and logs the change to CHANGELOG.md.
// Run via deploy.bat - not meant to be run standalone.
"use strict";
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const message = process.argv.slice(2).join(" ") || "Deploy";

const versionFile = path.join(root, "VERSION");
const [maj, min, pat] = fs.readFileSync(versionFile, "utf8").trim().split(".").map(Number);
const newVersion = `${maj}.${min}.${pat + 1}`;
fs.writeFileSync(versionFile, newVersion + "\n");

const now = new Date();
const stamp = now.toISOString().slice(0, 16).replace("T", " ");

const versionJs = `// Auto-generated by scripts/bump_version.js - do not edit by hand.
window.APP_VERSION='${newVersion}';
window.APP_BUILD_TIME='${stamp}';
`;
fs.writeFileSync(path.join(root, "web", "version.js"), versionJs);

const swPath = path.join(root, "web", "sw.js");
let sw = fs.readFileSync(swPath, "utf8");
sw = sw.replace(/const CACHE_NAME = '[^']*';/, `const CACHE_NAME = 'maslul-v${newVersion}';`);
fs.writeFileSync(swPath, sw);

const changelogPath = path.join(root, "CHANGELOG.md");
const changelog = fs.readFileSync(changelogPath, "utf8");
const lines = changelog.split("\n");
const headerEnd = lines.findIndex((l) => l.startsWith("`## v"));
const insertAt = headerEnd === -1 ? lines.length : headerEnd + 1;
lines.splice(insertAt, 0, `\n## v${newVersion} - ${stamp} - ${message}`);
fs.writeFileSync(changelogPath, lines.join("\n"));

console.log(newVersion);
